# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-19 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_restaurante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='restaurante',
        ),
    ]
