# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-19 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_delete_restaurante'),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='../static')),
                ('nombre', models.CharField(max_length=20)),
                ('valoracion', models.CharField(max_length=5)),
            ],
        ),
    ]
