# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-20 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20190619_1005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='restaurante',
        ),
    ]
